language: go
sudo: required
go:
  - 1.9
env:
  - PATH=/home/travis/gopath/bin:$PATH
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ruby ruby-dev build-essential rpm 
  - go get -u github.com/mitchellh/gox
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/alecthomas/gometalinter
install:
  - dep ensure
before_script:
  - gometalinter --install
    #  - gometalinter --vendor ./...
    #  - go tool vet *.go
script:
  - git status
        #  - gox -osarch="linux/amd64"
after_success:
  - gem install --no-ri --no-rdoc fpm
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: T4OUTRoWTjLrAXAel0PRcNFHFzKnH9o7aPJw0DXCFcbsYqka7QMPiNHvZWnDgNfA0uJhuDTaIQ3D/PS0iDpkfy+ouCod3nGShUtKQd95xI+bCuzD3UkMfxLS72bH7zzMABft2Ea8ofHdaKrLGasrGLZer4JRGrf/DO/IKxna3iKMb4ZgYjeqe+M+5k+7xtEBpe8QifppMxVEor+X9LkO34z6rMW8isEA1oTT39pax2ays6CbQgFIHAfU6rUmdNGX706h/RpVxhjleKFQ1v+QVfDgn/ZKCIqA9uoXUBuTelbFJjHKNRyQzRNLmxRoud1uF4oUy1tnhWlllLM49rmU0/WSKsS6m5aEB/afhiioVgbipnQWJ9zdW1zQnmfe2GDS8DMhWzRHVAUYFCUEnrmqQ6K4lJfofBWd7Hh+JTKEmG+cu5lD/cc1bUjEVRNJbbnQCaiY7eXza+NtrOUxo2nFCWCYdrpc7kkXnJNZKIfQ17v5HREIbfflldWvamyWcsFeYL4y3UcBBvb2jSgYil+JBbM7XqC/Nfn+XXmZOjwjDo8F0uXkSIRYWy29xI1VtUY3ccR+J+c+LzcfEn+IwcAkaCC0rfHRgPTQaF7whMKVFdD1KNy+Lc3p+mPjfhPpBmiIn60gK3vZ02OzMXVk1fGihaHWD4rTIUJMzby/ksKDk7Q=
  file_glob: true
  file:
    - dist/*/*
    - dist/*.deb
    - dist/*.rpm
    - dist/*.tar.gz
    - dist/*.checksums.txt
  on:
    tags: true
    repo: sofixa/vsphere-influxdb-go
    all_branches: true

